### ISSUE TITLE
Increase innodb_buffer_pool_size & innodb_log_file_size

### ISSUE THREAD

**Issue by fortis** [Wodby/drupal-mariadb#1]
Getting an error on import database:
> Error at query 222: The size of BLOB/TEXT data inserted in one transaction is greater than 10% of redo log size. Increase the redo log size using innodb_log_file_size.
Let's increase to innodb_log_file_size = 64Mb

Also there is innodb_buffer_pool_size = 64Mb, maybe better to increase that to 1G (docker allocates 2G RAM by default)

**Comment by PavelPrischepa** [comment]
Thank you for the suggestion. Done.

**Comment by fortis** [comment]
innodb_log_file_size still smaller, provided PR will fix that error (increase from 16 to 32 Mb)
