### ISSUE TITLE
Upgrade to php7

### ISSUE THREAD

**Issue by martinfrances107** [Wodby/drupal-mariadb#3]
I really like this container eco-system

The jury is in on php7 it has a greatly reduced memory footprint, and is a marked performance speedup.

Without any profiling  - I think it is universally true that modernizing the mariadb container to an image in which the underlying PHP is a version 7 variant would be a good thing.

Here is the "web server" definition reported by the user interface. 

PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.26

I think we need to move the alpine base image as defined in Dockefile away from "alpine:3.4" to an image that supports the latest php 7.0.x image.

**Comment by PavelPrischepa** [comment]
@martinfrances107 PHP 7 is already supported, just replace `image: wodby/drupal-php:5.6` by `image: wodby/drupal-php:7.0` in php service in docker-compose.yml

**Comment by martinfrances107** [comment]
Thank you, I was  aware of that.... but I am talking about a really minor issue AWAY from the "main line" the  chain of containers that handle the sites public web requests.

This issue is incorrectly linked to the drupal-mariadb container subproject - my mistake It should be linked to the subproject that creates the pma image.

Specifically the php thread running inside that container - and is there only to serve the private/backend web site for  admins who want  direct access to the database.

My plan over the next week is to select a more up to date base image from which to start....

**Comment by PavelPrischepa** [comment]
btw, we use the official PMA image https://github.com/phpmyadmin/docker.

**Comment by martinfrances107** [comment]
Thanks, 

An extract from the repos  Dockerfile

RUN apk add --no-cache php5-mysqli php5-ctype php5-xml php5-gd php5-zlib php5-bz2 php5-zip php5-openssl php5-curl php5-opcache php5-json nginx php5-fpm supervisor
 
Using the official repo is the way to go .... there are benefits to just having something standard that justs plugs in and does its job....Oh well they will adapt in time.
